services:
  mysql:
    image: 'mysql:9.7.0'
    container_name: 'login_db'
    environment:
      - 'MYSQL_DATABASE=login_db'
      - 'MYSQL_USER=username'
      - 'MYSQL_PASSWORD==password'
      - 'MYSQL_ROOT_PASSWORD=root_password'
    ports:
      - '3306:3306'
