spring.application.name=login
spring.profiles.active=local
# JWT:
jwt.secret=UAAPmNht7HxalOo4j+AmwfhSGVF8C4dIjV5CkZKqEMQ=
jwt.expiration=3600000
# logging:
logging.level.root=info
logging.level.org.springframework.web=info
logging.level.org.hibernate=info
