# JWT:
jwt.expiration=900000
# root logger
rootLogger=INFO, STDOUT
# logging:
logging.level.root=info
logging.level.org.springframework.web=info
logging.level.org.hibernate=info
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
