spring.profiles.active=local
spring.application.name=login
# JPA:
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# JWT:
jwt.secret=UAAPmNht7HxalOo4j+AmwfhSGVF8C4dIjV5CkZKqEMQ=
jwt.expiration=3600000
