spring.config.import=classpath:secrets-prod.properties
# MySQL:
spring.datasource.url=jdbc:mysql://mysql:3306/login_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=user3O1
# JPA:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
