name: Login CI
on: [ push, pull_request ]

jobs:
  spring-boot-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '26'
          cache: 'gradle'
          distribution: 'temurin'

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Run tests with Gradle Wrapper
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew test

  angular-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: './front-end/package-lock.json'

      - name: Install dependencies
        working-directory: './front-end'
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Run Angular tests
        working-directory: './front-end'
        run: npm run test-ci
